modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Always%20a%20Wither%20Skull"
logoFile="icon.png"

[[mods]]
modId="alwaysawitherskull"
version="3.3"
displayName="Always a Wither Skull"
displayURL="https://serilum.com/mod/always-a-wither-skull"
authors="Rick South"
description='''A drag-and-drop mod that makes wither skeletons always drop their skull on death.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.alwaysawitherskull]]
    modId="collective"
    mandatory=true
    versionRange="[7.67,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alwaysawitherskull]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
